[phases.setup]
nixpkgs = [
  "python311",
  "zlib",
  "libjpeg",
  "gcc",
  "pkg-config"
]

[phases.build]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "streamlit run app.py --server.port 8000 --server.address 0.0.0.0"
